### ISSUE TITLE
The integration test fails from time to time. Why?

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1574]
Both locally and in [github action](https://github.com/objectionary/eo/actions/runs/3713442725/jobs/6296093058) from run to run this error appears in `eo-maven-plugin`, even though I don't change the code.

@volodya-lombrozo, Can you pls help why it is happening?

```
[INFO] 
Warning:  Tests run: 169, Failures: 0, Errors: 0, Skipped: 3
[INFO] 
[INFO] 
[INFO] --- jcabi-maven-plugin:0.17.0:versionalize (jcabi-versionalize-packages) @ eo-maven-plugin ---
[INFO] Versionalizing /Users/runner/work/eo/eo/eo-maven-plugin/target/classes directory
[INFO] File /Users/runner/work/eo/eo/eo-maven-plugin/target/classes/org/eolang/maven/objectionary/org-eolang-eo-maven-plugin-maven-plugin.txt added
[INFO] File /Users/runner/work/eo/eo/eo-maven-plugin/target/classes/org/eolang/maven/util/org-eolang-eo-maven-plugin-maven-plugin.txt added
[INFO] File /Users/runner/work/eo/eo/eo-maven-plugin/target/classes/org/eolang/maven/hash/org-eolang-eo-maven-plugin-maven-plugin.txt added
[INFO] File /Users/runner/work/eo/eo/eo-maven-plugin/target/classes/org/eolang/maven/optimization/org-eolang-eo-maven-plugin-maven-plugin.txt added
[INFO] File /Users/runner/work/eo/eo/eo-maven-plugin/target/classes/org/eolang/maven/footprint/org-eolang-eo-maven-plugin-maven-plugin.txt added
[INFO] File /Users/runner/work/eo/eo/eo-maven-plugin/target/classes/org/eolang/maven/org-eolang-eo-maven-plugin-maven-plugin.txt added
[INFO] 
[INFO] --- maven-jar-plugin:3.3.0:jar (default-jar) @ eo-maven-plugin ---
[INFO] Building jar: /Users/runner/work/eo/eo/eo-maven-plugin/target/eo-maven-plugin-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-plugin-plugin:3.6.4:addPluginArtifactMetadata (default-addPluginArtifactMetadata) @ eo-maven-plugin ---
[INFO] 
[INFO] --- maven-invoker-plugin:3.3.0:install (default) @ eo-maven-plugin ---
[INFO] Installing /Users/runner/work/eo/eo/eo-parser/pom.xml to /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-parser/1.0-SNAPSHOT/eo-parser-1.0-SNAPSHOT.pom
[INFO] Installing /Users/runner/work/eo/eo/eo-parser/target/eo-parser-1.0-SNAPSHOT.jar to /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-parser/1.0-SNAPSHOT/eo-parser-1.0-SNAPSHOT.jar
[INFO] Installing /Users/runner/work/eo/eo/pom.xml to /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-parent/1.0-SNAPSHOT/eo-parent-1.0-SNAPSHOT.pom
[INFO] Installing /Users/runner/work/eo/eo/eo-maven-plugin/pom.xml to /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-maven-plugin/1.0-SNAPSHOT/eo-maven-plugin-1.0-SNAPSHOT.pom
[INFO] Installing /Users/runner/work/eo/eo/eo-maven-plugin/target/eo-maven-plugin-1.0-SNAPSHOT.jar to /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-maven-plugin/1.0-SNAPSHOT/eo-maven-plugin-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-invoker-plugin:3.3.0:run (default) @ eo-maven-plugin ---
[INFO] Building: fibonacci/pom.xml
[INFO] run post-build script verify.groovy
[INFO]   Assertion Error
[INFO]           fibonacci/pom.xml ................................ FAILED (33.9 s)
Error:  -------------------------------------------------
Error:  

*** begin build.log for: fibonacci/pom.xml ***
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.eolang:examples >-------------------------
[INFO] Building Fibonacci Numbers Calculator 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.2.0:clean (default-clean) @ examples ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.1.0:enforce (enforce-maven) @ examples ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:3.0.0:create (jcabi-build-number) @ examples ---
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd '/Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci' && 'git' 'rev-parse' '--verify' '--short=7' 'HEAD'
[INFO] Working directory: /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci
[INFO] Storing buildNumber: 42f5fad at timestamp: 2022-12-16T13:19:19
Warning:  Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd '/Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci' && 'git' 'rev-parse' '--verify' '--short=7' 'HEAD'
[INFO] Working directory: /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- buildnumber-maven-plugin:3.0.0:create-timestamp (jcabi-build-number) @ examples ---
[INFO] Skipping because we are not in root module.
[INFO] 
[INFO] --- eo-maven-plugin:1.0-SNAPSHOT:register (default) @ examples ---
[INFO] Registered 3 EO sources from ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/src/main/eo to ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/foreign.csv, included [**.eo], excluded []
[INFO] 
[INFO] --- eo-maven-plugin:1.0-SNAPSHOT:assemble (default) @ examples ---
[INFO] 0 attributes loaded from 36 stream(s) in 126ms, 48 saved, 430 ignored: []
[INFO] Parsed 3 .eo sources to XMIRs
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/examples/fibonacci.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/examples/longname.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/examples/app.xmir
[INFO] Running 3 optimizations in parallel
Warning:  XSL 'not-empty-atoms' took 252ms (over 100ms)
Warning:  XSL 'not-empty-atoms' took 259ms (over 100ms)
Warning:  XSL 'not-empty-atoms' took 286ms (over 100ms)
Warning:  XSL 'not-empty-atoms' took 358ms (over 100ms)
Warning:  XSL 'not-empty-atoms' took 368ms (over 100ms)
Warning:  XSL 'not-empty-atoms' took 378ms (over 100ms)
Warning:  XSL 'broken-aliases' took 116ms (over 100ms)
Warning:  XSL 'broken-aliases' took 124ms (over 100ms)
Warning:  XSL 'broken-aliases' took 135ms (over 100ms)
Warning:  XSL 'broken-aliases' took 150ms (over 100ms)
Warning:  XSL 'duplicate-aliases' took 111ms (over 100ms)
Warning:  XSL 'duplicate-aliases' took 114ms (over 100ms)
Warning:  XSL 'vars-float-up' took 103ms (over 100ms)
Warning:  XSL 'vars-float-up' took 118ms (over 100ms)
Warning:  XSL 'set-locators' took 103ms (over 100ms)
Warning:  XSL 'globals-to-abstracts' took 101ms (over 100ms)
Warning:  XSL 'globals-to-abstracts' took 126ms (over 100ms)
Warning:  XSL 'remove-levels' took 2s (over 100ms)
Warning:  XSL 'abstracts-float-up' took 2s (over 100ms)
Warning:  XSL 'broken-refs' took 2s (over 100ms)
Warning:  XSL 'abstracts-float-up' took 2s (over 100ms)
Warning:  XSL 'broken-refs' took 2s (over 100ms)
Warning:  XSL 'add-refs' took 102ms (over 100ms)
[INFO] Optimized 3 out of 3 XMIR program(s)
[INFO] Discovered 7 foreign objects in 3 programs: [org.eolang.io.stdout, org.eolang.bool, org.eolang.txt.sprintf, org.eolang.string, org.eolang.examples.fibonacci, org.eolang.int, org.eolang.array]
[INFO] 6 program(s) pulled from [./Users/runner/.eo (9a2271f)]+[fallback to [https://raw.githubusercontent.com/objectionary/home/%s/objects/%s.eo]+(9a2271f cache to /Users/runner/.eo)]
[INFO] Configured Artifact: org.eolang:eo-runtime:0.28.11:jar
[INFO] Unpacking /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-runtime/0.28.11/eo-runtime-0.28.11.jar to /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.11 with includes "" and excludes ""
[INFO] org.eolang:eo-runtime::0.28.11 unpacked to ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.11
[INFO] Found 28 new file(s) after unpacking of org.eolang:eo-runtime:0.28.11
[INFO] New 1 dependenc(ies) unpacked
[INFO] Found 20 sources in ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.11/EO-SOURCES, 20 program(s) registered with version 0.28.11
[INFO] New 20 objects found in 1 unpacked dependencies
[INFO] Placed 8 binary file(s) out of 28, found in org.eolang/eo-runtime/-/0.28.11
[INFO] Placed 8 binary files found in 1 dependencies
[INFO] Assemble cycle #1 (eo:3/xmir:0/xmir2:0/discovered:0 -> eo:9/xmir:3/xmir2:3/discovered:3), took 12s
Warning:  (*)
[INFO] Parsed 6 .eo sources to XMIRs
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/int.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/bool.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/array.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/io/stdout.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/string.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/txt/sprintf.xmir
[INFO] Running 6 optimizations in parallel
[INFO] Optimized 6 out of 9 XMIR program(s)
[INFO] Discovered 4 foreign objects in 6 programs: [org.eolang.bytes, org.eolang.array, org.eolang.int, org.eolang.collections.list]
[INFO] 16 program(s) pulled from [./Users/runner/.eo (9a2271f)]+[fallback to [https://raw.githubusercontent.com/objectionary/home/%s/objects/%s.eo]+(9a2271f cache to /Users/runner/.eo)]
[INFO] Dependency found for org.eolang.int/*.*.*: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.bool/*.*.*: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.array/*.*.*: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.io.stdout/*.*.*: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.string/*.*.*: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.txt.sprintf/*.*.*: org.eolang:eo-strings:0.0.4
[INFO] Configured Artifact: org.eolang:eo-runtime:0.28.10:jar
[INFO] Unpacking /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-runtime/0.28.10/eo-runtime-0.28.10.jar to /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.10 with includes "" and excludes ""
[INFO] org.eolang:eo-runtime::0.28.10 unpacked to ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.10
[INFO] Found 144 new file(s) after unpacking of org.eolang:eo-runtime:0.28.10
[INFO] Configured Artifact: org.eolang:eo-strings:0.0.4:jar
[INFO] Unpacking /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-strings/0.0.4/eo-strings-0.0.4.jar to /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-strings/-/0.0.4 with includes "" and excludes ""
[INFO] org.eolang:eo-strings::0.0.4 unpacked to ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-strings/-/0.0.4
[INFO] Found 27 new file(s) after unpacking of org.eolang:eo-strings:0.0.4
[INFO] New 2 dependenc(ies) unpacked
[INFO] Found 4 sources in ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-strings/-/0.0.4/EO-SOURCES, 4 program(s) registered with version 0.0.4
[INFO] Found 20 sources in ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.11/EO-SOURCES, 20 program(s) registered with version 0.28.11
[INFO] Found 20 sources in ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.10/EO-SOURCES, 20 program(s) registered with version 0.28.10
[INFO] New 44 objects found in 3 unpacked dependencies
[INFO] Placed 22 binary file(s) out of 27, found in org.eolang/eo-strings/-/0.0.4
[INFO] Found placed binaries from org.eolang/eo-runtime/-/0.28.11
[INFO] No binary file(s) out of 28 were placed from org.eolang/eo-runtime/-/0.28.11
[INFO] Placed 120 binary file(s) out of 144, found in org.eolang/eo-runtime/-/0.28.10
[INFO] Placed 142 binary files found in 3 dependencies
[INFO] Assemble cycle #2 (eo:9/xmir:3/xmir2:3/discovered:3 -> eo:25/xmir:9/xmir2:9/discovered:9), took 7s
Warning:  (acc-index.at 0)
Warning:  (acc-index.at 1)
Warning:  (index.lt (carr.length))
Warning:  (carr.at index)
Warning:  (index.plus 1)
Warning:  (acc-index.at 0)
Warning:  (acc-index.at 1)
Warning:  (index.lt (carr.length))
Warning:  (carr.at index)
Warning:  (index.plus 1)
[INFO] Parsed 16 .eo sources to XMIRs
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/bytes.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/seq.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/as-phi.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/rust.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/ram.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/nop.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/io/stdin.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/cage.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/float.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/switch.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/try.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/memory.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/goto.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/error.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/heap.xmir
[INFO] Adding optimization task for /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/01-parse/org/eolang/collections/list.xmir
[INFO] Running 16 optimizations in parallel
Warning:  XSL 'unknown-names' took 145ms (over 100ms)
Warning:  XSL 'unknown-names' took 102ms (over 100ms)
Warning:  XSL 'noname-attributes' took 200ms (over 100ms)
Warning:  XSL 'unused-aliases' took 197ms (over 100ms)
Warning:  XSL 'broken-refs' took 195ms (over 100ms)
Warning:  XSL 'noname-attributes' took 207ms (over 100ms)
Warning:  XSL 'unused-aliases' took 204ms (over 100ms)
Warning:  XSL 'broken-refs' took 223ms (over 100ms)
Warning:  XSL 'set-locators' took 163ms (over 100ms)
Warning:  XSL 'globals-to-abstracts' took 158ms (over 100ms)
Warning:  XSL 'set-locators' took 180ms (over 100ms)
Warning:  XSL 'globals-to-abstracts' took 173ms (over 100ms)
Warning:  XSL 'mandatory-package-meta' took 187ms (over 100ms)
[INFO] Optimized 16 out of 25 XMIR program(s)
[INFO] Discovered 9 foreign objects in 16 programs: [org.eolang.error, org.eolang.bool, org.eolang.collections.list, org.eolang.string, org.eolang.collections.bytes-as-array, org.eolang.memory, org.eolang.array, org.eolang.int, org.eolang.seq]
[INFO] 4 program(s) pulled from [./Users/runner/.eo (9a2271f)]+[fallback to [https://raw.githubusercontent.com/objectionary/home/%s/objects/%s.eo]+(9a2271f cache to /Users/runner/.eo)]
[INFO] Dependency found for org.eolang.bytes/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.seq/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.as-phi/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.rust/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.ram/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.nop/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.io.stdin/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.cage/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.float/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.switch/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.try/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.memory/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.goto/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.error/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.heap/0.28.11: org.eolang:eo-runtime:0.28.10
[INFO] Dependency found for org.eolang.collections.list/*.*.*: org.eolang:eo-collections:0.0.4
[INFO] Configured Artifact: org.eolang:eo-collections:0.0.4:jar
[INFO] Unpacking /Users/runner/work/eo/eo/eo-maven-plugin/target/local-repo/org/eolang/eo-collections/0.0.4/eo-collections-0.0.4.jar to /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-collections/-/0.0.4 with includes "" and excludes ""
[INFO] org.eolang:eo-collections::0.0.4 unpacked to ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-collections/-/0.0.4
[INFO] Found 9 new file(s) after unpacking of org.eolang:eo-collections:0.0.4
[INFO] New 2 dependenc(ies) unpacked
[INFO] Found 4 sources in ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-collections/-/0.0.4/EO-SOURCES, 4 program(s) registered with version 0.0.4
[INFO] Found 4 sources in ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-strings/-/0.0.4/EO-SOURCES, 4 program(s) registered with version 0.0.4
[INFO] Found 20 sources in ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.11/EO-SOURCES, 20 program(s) registered with version 0.28.11
[INFO] Found 20 sources in ./Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/eo/06-resolve/org.eolang/eo-runtime/-/0.28.10/EO-SOURCES, 20 program(s) registered with version 0.28.10
[INFO] New 48 objects found in 4 unpacked dependencies
[INFO] Placed 4 binary file(s) out of 9, found in org.eolang/eo-collections/-/0.0.4
[INFO] Found placed binaries from org.eolang/eo-strings/-/0.0.4
[INFO] No binary file(s) out of 27 were placed from org.eolang/eo-strings/-/0.0.4
[INFO] Found placed binaries from org.eolang/eo-runtime/-/0.28.11
[INFO] Placed 4 binary file(s) out of 28, found in org.eolang/eo-runtime/-/0.28.11
[INFO] Found placed binaries from org.eolang/eo-runtime/-/0.28.10
[INFO] Placed 4 binary file(s) out of 144, found in org.eolang/eo-runtime/-/0.28.10
[INFO] Placed 12 binary files found in 4 dependencies
[INFO] Assemble cycle #3 (eo:25/xmir:9/xmir2:9/discovered:9 -> eo:29/xmir:25/xmir2:25/discovered:25), took 8s
Warning:  (text "")
Warning:  (text "")
Warning:  (match txt)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.307 s
[INFO] Finished at: 2022-12-16T13:19:45Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.eolang:eo-maven-plugin:1.0-SNAPSHOT:assemble (default) on project examples: 'org.eolang.maven.AssembleMojo@26582ca' execution failed: java.lang.IllegalStateException: org.apache.maven.plugin.MojoExecutionException: 'org.eolang.maven.ParseMojo@1a7c216' execution failed: java.lang.IllegalArgumentException: No value present: java.util.NoSuchElementException: No value present -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eolang:eo-maven-plugin:1.0-SNAPSHOT:assemble (default) on project examples: 'org.eolang.maven.AssembleMojo@26582ca' execution failed
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: 'org.eolang.maven.AssembleMojo@26582ca' execution failed
    at org.eolang.maven.SafeMojo.execute (SafeMojo.java:246)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: org.apache.maven.plugin.MojoExecutionException: 'org.eolang.maven.ParseMojo@1a7c216' execution failed
    at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    at java.util.concurrent.FutureTask.get (FutureTask.java:205)
    at org.eolang.maven.SafeMojo.execWithTimeout (SafeMojo.java:318)
    at org.eolang.maven.SafeMojo.execute (SafeMojo.java:219)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.IllegalStateException: org.apache.maven.plugin.MojoExecutionException: 'org.eolang.maven.ParseMojo@1a7c216' execution failed
    at org.eolang.maven.Moja.execute (Moja.java:124)
    at org.eolang.maven.AssembleMojo.exec (AssembleMojo.java:237)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: org.apache.maven.plugin.MojoExecutionException: 'org.eolang.maven.ParseMojo@1a7c216' execution failed
    at org.eolang.maven.SafeMojo.execute (SafeMojo.java:246)
    at org.eolang.maven.Moja.execute (Moja.java:120)
    at org.eolang.maven.AssembleMojo.exec (AssembleMojo.java:237)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No value present
    at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    at java.util.concurrent.FutureTask.get (FutureTask.java:205)
    at org.eolang.maven.SafeMojo.execWithTimeout (SafeMojo.java:318)
    at org.eolang.maven.SafeMojo.execute (SafeMojo.java:219)
    at org.eolang.maven.Moja.execute (Moja.java:120)
    at org.eolang.maven.AssembleMojo.exec (AssembleMojo.java:237)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.IllegalArgumentException: No value present
    at org.eolang.maven.ParseMojo.exec (ParseMojo.java:162)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: No value present
    at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    at java.util.concurrent.FutureTask.get (FutureTask.java:191)
    at org.eolang.maven.ParseMojo.exec (ParseMojo.java:159)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.util.NoSuchElementException: No value present
    at java.util.Optional.get (Optional.java:148)
    at com.yegor256.tojos.MonoTojo.get (MonoTojo.java:73)
    at org.eolang.maven.ParseMojo.parse (ParseMojo.java:196)
    at org.eolang.maven.ParseMojo.lambda$exec$1 (ParseMojo.java:139)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Error:  
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Running post-build script: /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/verify.groovy
Assertion failed: 

assert new File(basedir, it).exists()
       |        |        |   |
       |        |        |   false
       |        |        'target/generated-sources/EOorg/EOeolang/EOexamples/EOapp.java'
       |        /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci
       /Users/runner/work/eo/eo/eo-maven-plugin/target/it/fibonacci/target/generated-sources/EOorg/EOeolang/EOexamples/EOapp.java

	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:436)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at Script1$_run_closure1.doCall(Script1.groovy:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2384)
	at org.codehaus.groovy.runtime.dgm$202.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script1.run(Script1.groovy:43)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
	at org.apache.maven.shared.scriptinterpreter.GroovyScriptInterpreter.evaluateScript(GroovyScriptInterpreter.java:76)
	at org.apache.maven.shared.scriptinterpreter.ScriptRunner.executeRun(ScriptRunner.java:236)
	at org.apache.maven.shared.scriptinterpreter.ScriptRunner.run(ScriptRunner.java:161)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runPostBuildHook(AbstractInvokerMojo.java:2154)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:2129)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:1721)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.lambda$runBuilds$4(AbstractInvokerMojo.java:1431)
	at org.apache.maven.plugins.invoker.JobExecutor.lambda$null$1(JobExecutor.java:69)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
*** end build.log for: fibonacci/pom.xml ***

Error:  -------------------------------------------------
Error:  
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
Error:  The following builds failed:
Error:  *  fibonacci/pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eo 1.0-SNAPSHOT:
[INFO] 
[INFO] eo ................................................. SUCCESS [  6.331 s]
[INFO] eo-parser .......................................... SUCCESS [ 26.631 s]
[INFO] eo-maven-plugin .................................... FAILURE [01:12 min]
[INFO] eo-runtime ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by volodya-lombrozo** [comment]
@MikhailLipanin does it happen locally on your machine? Do you have another pipelines with the same issue?

**Comment by volodya-lombrozo** [comment]
@yegor256 assign to me

**Comment by MikhailLipanin** [comment]
@volodya-lombrozo Yes, right now I run full `eo` cycle, which at first time get this error in `Optional`, but in the second time I got `SUCCESS`. Then I pushed to PR and `github-action` build again gets this error...

**Comment by mximp** [comment]
@volodya-lombrozo have the same issue locally in approx. 1 out of 3 runs

**Comment by 0pdd** [comment]
@MikhailLipanin the puzzle [#1607](https://github.com/objectionary/eo/issues/1607) is still not solved.

**Comment by 0pdd** [comment]
@MikhailLipanin the only puzzle [#1607](https://github.com/objectionary/eo/issues/1607) is solved here.
