### ISSUE TITLE
sonarcube is complaining about our quality of code

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1897]
We have pretty bad results in SonarCube: https://sonarcloud.io/summary/new_code?id=com.objectionary%3Aeo Let's try to fix at least the major problems.

**Comment by yegor256** [comment]
@mximp pls, take a look at this one

**Comment by mximp** [comment]
@yegor256 Can you please provide settings for `objectionary/eo` SonarCloud, specifically what filters are set up for the sources scope (inclusions/exclusions).
I believe only admins can see that.

I want to set the same setting for the fork to validate the changes, given that checks fo PRs don't seems to work in SonarCloud.

**Comment by yegor256** [comment]
@mximp I didn't configure anything in SonarCube. It's a default configuration. All defects you can see here: https://sonarcloud.io/summary/new_code?id=com.objectionary%3Aeo I suggest we just fix them one by one.

**Comment by yegor256** [comment]
@mximp once we fix all problems in the repo, I suggest we configure our build to fail when SonarCube complains. I configured `xembly` repo this way and it works fine: https://github.com/yegor256/xembly/commit/f23e3cc7116e585e9414511650d009b7be8da313

**Comment by mximp** [comment]
> @mximp I didn't configure anything in SonarCube. It's a default configuration. All defects you can see here: https://sonarcloud.io/summary/new_code?id=com.objectionary%3Aeo I suggest we just fix them one by one.

@yegor256 That makes sense. The only question here - how do we validate that we fixed particular problem. I was thinking about setting up separate SonarCloud project for at lease forked branch - but for that I need the same settings as for objectionary/master.

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1959](https://github.com/objectionary/eo/issues/1959), [#1960](https://github.com/objectionary/eo/issues/1960), [#1961](https://github.com/objectionary/eo/issues/1961) are still not solved; solved: [#1962](https://github.com/objectionary/eo/issues/1962).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1959](https://github.com/objectionary/eo/issues/1959), [#1961](https://github.com/objectionary/eo/issues/1961) are still not solved; solved: [#1960](https://github.com/objectionary/eo/issues/1960), [#1962](https://github.com/objectionary/eo/issues/1962).

**Comment by mximp** [comment]
@yegor256 all tasks have been completed. The issue can be closed.

**Comment by yegor256** [comment]
@mximp how do you measure? I still see issues reported (5 critical): https://sonarcloud.io/summary/new_code?id=com.objectionary%3Aeo

**Comment by yegor256** [comment]
@mximp try to run it like this:

```
$ mvn --batch-mode -DskipTests -Dinvoker.skip verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true
```

You will see what happens.

When this task is complete, we can add `-Dsonar.qualitygate.wait=true` to the command inside `sonar.yml` and this action will pass

**Comment by mximp** [comment]
> @mximp how do you measure? I still see issues reported (5 critical): https://sonarcloud.io/summary/new_code?id=com.objectionary%3Aeo

@yegor256 At the moment we have only two minor bugs. I believe the scope of this issue has been completed.
It's probably better to create new issues for raised problems

**Comment by mximp** [comment]
> @mximp try to run it like this:
> 
> ```
> $ mvn --batch-mode -DskipTests -Dinvoker.skip verify \
>   org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true
> ```
> 
> You will see what happens.
> 
> When this task is complete, we can add `-Dsonar.qualitygate.wait=true` to the command inside `sonar.yml` and this action will pass

@yegor256 I can see this [job](https://github.com/objectionary/eo/actions/workflows/sonar.yml) is green already in Github Actions for eo.
Maybe we can enable it already?

**Comment by yegor256** [comment]
@mximp yes, let's do it

**Comment by 0pdd** [comment]
@yegor256 all 4 puzzles are solved here: [#1959](https://github.com/objectionary/eo/issues/1959), [#1960](https://github.com/objectionary/eo/issues/1960), [#1961](https://github.com/objectionary/eo/issues/1961), [#1962](https://github.com/objectionary/eo/issues/1962).
