### ISSUE TITLE
Bug in phi-calculus parser

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2930]
[This](https://github.com/objectionary/eo/issues/2873#issuecomment-1983718532) comment shows that there's a bug in phi-calculus parser.

**Comment by maxonfjvipon** [comment]
After parsing this phi:
```
{
  ⟦
    test ↦ ⟦
      α1 ↦ ⟦⟧.plus(
        α0 ↦ Φ.org.eolang.int
      )
    ⟧
  ⟧
}
```
we get the next XMIR:
```xml
<program dob="2023-03-19T00:00:00"
         name="main"
         revision="1234567"
         time="2024-03-08T08:51:26.339569Z"
         version="0.0-SNAPSHOT"><!--This is XMIR - a dialect of XML, which is used to present a parsed EO program. For more information please visit https://news.eolang.org/2022-11-25-xmir-guide.html-->
   <listing>{
  ⟦
    test ↦ ⟦
      α1 ↦ ⟦⟧.plus(
        α0 ↦ Φ.org.eolang.int
      )
    ⟧
  ⟧
}</listing>
   <errors/>
   <sheets/>
   <license/>
   <metas/>
   <objects ms="4">
      <o line="3" pos="4">
         <o abstract="" line="4" name="1" pos="6">
            <o base=".plus" line="4" method="" name="test" pos="13">
               <o base="Q" line="5" pos="8"/>
               <o base=".org" line="5" method="" pos="14"/>
               <o base=".eolang" line="5" method="" pos="18"/>
               <o as="0" base=".int" line="5" method="" pos="25"/>
            </o>
         </o>
      </o>
   </objects>
</program>
```

It's definitely wrong.

I guess the main problem here is in parsing `dispatch` after `formation`.

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.35.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.9`

**Comment by maxonfjvipon** [comment]
@deemp I think the bug is fixed. Please use `--parser=0.35.9` in your pipeline

**Comment by deemp** [comment]
@maxonfjvipon, bool-tests still fail. Have you tested the fixes on eo-runtime tests? Are you going to test your fixes on eo-runtime tests?

I made https://github.com/objectionary/eo/pull/2929 that allows to test phi -> unphi on a subset of eo-runtime tests. Do you need my assistance in configuring the tests?

**Comment by maxonfjvipon** [comment]
`phi` and `unphi` goals work fine. But EO grammar does not support the one specific case - vertical method after formation:
```
[]
.method
```
It seems we should allow such syntax, because there's no other way we can print XMIR to EO in straight notation
