### ISSUE TITLE
Argument values are not passed to `sprintf`

### ISSUE THREAD

**Issue by Suban05** [objectionary/eo#3990]
I have the following eo program:

```
+package sandbox
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

# Outputs the age.
[args] > app
  args.at 0 > age
  stdout > @
    sprintf
      "I am %d years old!"
      age
```

I run

```
java -cp target/classes org.eolang.Main sandbox.app 10
```

I get the error:

```
Dataized to org.eolang.error with Φ.org.eolang.string inside, at:
  ⇢  1) Error in "Φ.org.eolang.tuple.at.Δ" at org.eolang.tuple:34:2
  ⇢  2) Error in "Φ.org.eolang.tuple.at.φ.Δ" at org.eolang.tuple:40:4
  ⇢  3) Error in "Φ.org.eolang.false.if.Δ" at org.eolang.false:16:2
  ⇢  4) Error in "Φ.org.eolang.false.if.φ.Δ" at org.eolang.false:16:2
  ⇢  5) Error in "Φ.org.eolang.tuple.at.φ.α1.Δ" at org.eolang.tuple:45:6
  ⇢  6) Error in "Φ.org.eolang.tuple.at.at-fast.Δ" at org.eolang.tuple:47:4
  ⇢  7) Error in "Φ.org.eolang.tuple.at.at-fast.φ.Δ" at org.eolang.tuple:48:6
  ⇢  8) Error in "Φ.org.eolang.false.if.Δ" at org.eolang.false:16:2
  ⇢  9) Error in "Φ.org.eolang.false.if.φ.Δ" at org.eolang.false:16:2
  ⇢ 10) Error in "Φ.org.eolang.tuple.at.at-fast.φ.α1.Δ" at org.eolang.tuple:51:8
  ⇢ 11) Error in "Φ.org.eolang.tuple.at.at-fast.Δ" at org.eolang.tuple:47:4
  ⇢ 12) Error in "Φ.org.eolang.tuple.at.at-fast.φ.Δ" at org.eolang.tuple:48:6
  ⇢ 13) Error in "Φ.org.eolang.true.if.Δ" at org.eolang.true:16:2
  ⇢ 14) Error in "Φ.org.eolang.true.if.φ.Δ" at org.eolang.true:16:2
  ⇢ 15) Error in "Φ.org.eolang.tuple.at.at-fast.φ.α0.Δ" at org.eolang.tuple:50:11
  ⇢ 16) Error in "Φ.org.eolang.tuple.with.φ.ρ.α1.Δ" at org.eolang.tuple:58:8
  ⇢ 17) Error in "Φ.org.eolang.io.console.posix-console.write.output-block.write.φ.ρ.α0.ρ.α0.ρ.α1.ρ.α0.Δ" at org.eolang.io.console:126:40
  ⇢ 18) Error in "Φ.org.eolang.io.console.posix-console.write.φ.ρ.α0.Δ" at org.eolang.io.console:108:26
  ⇢ 19) Error in "Φ.org.eolang.io.stdout.φ.α0.ρ.α0.α0.Δ" at org.eolang.io.stdout:20:18
  ⇢ 20) Error in "Φ.sandbox.app.φ.α0.Δ" at sandbox.app:11:4
  ⇢ 21) Error in "Φ.sandbox.app.φ.α0.α1" at sandbox.app:13:6
  ⇢ 22) Error in "Φ.sandbox.app.age" at sandbox.app:9:6
  ⇢ 23) Error in "Φ.org.eolang.tuple.at" at org.eolang.tuple:34:2
  ⇢ 24) Error in "Φ.org.eolang.tuple.at.φ" at org.eolang.tuple:40:4
  ⇢ 25) Error in "Φ.org.eolang.tuple.at.φ.ρ" at org.eolang.tuple:41:6
  ⇢ 26) Error in "Φ.org.eolang.false.or" at org.eolang.false:24:2
  ⇢ 27) Error in "Φ.org.eolang.false.or.φ" at org.eolang.false:24:5
  ⇢ 28) Error in "Φ.org.eolang.bytes.eq" at org.eolang.bytes:70:2
  ⇢ 29) Error in "Φ.org.eolang.false.or.φ.α0" at org.eolang.false:24:9
  ⇢ 30) Error in "Φ.org.eolang.tuple.at.φ.ρ.α0" at org.eolang.tuple:43:14
  ⇢ 31) Error in "Φ.org.eolang.tuple.with.φ.ρ.α2" at org.eolang.tuple:59:23
  ⇢ 32) Error in "Φ.org.eolang.tuple.with.φ.ρ.α2.ρ" at org.eolang.tuple:59:15
  ⇢ 33) "The attribute "length" is not initialized, can't read"
Dataized to org.eolang.error with org.eolang.dataized.φ.α1.φ.α0 inside, at:
  ⇢ 1) Error in "Φ.org.eolang.dataized.φ.α1.φ.Δ" at org.eolang.dataized:39:4
Dataized to org.eolang.error with org.eolang.dataized.φ.α1.φ.α0 inside, at:
  ⇢  1) Error in "Φ.org.eolang.dataized.φ.α0.Δ" at org.eolang.dataized:38:4
  ⇢  2) Error in "Φ.org.eolang.seq.loop.φ.α1.ρ.ρ.ρ.α0.Δ" at org.eolang.seq:32:21
  ⇢  3) Error in "Φ.org.eolang.tuple.empty.with.φ.ρ.α1.Δ" at org.eolang.tuple:30:10
  ⇢  4) Error in "Φ.org.eolang.io.stdout.φ.α0.ρ.α0.Δ" at org.eolang.io.stdout:20:11
  ⇢  5) Error in "Φ.org.eolang.io.console.posix-console.write.Δ" at org.eolang.io.console:107:4
  ⇢  6) Error in "Φ.org.eolang.io.console.posix-console.write.φ" at org.eolang.io.console:108:33
  ⇢  7) Error in "Φ.org.eolang.io.console.posix-console.write.φ.ρ" at org.eolang.io.console:108:19
  ⇢  8) Error in "Φ.org.eolang.io.console.posix-console.write.output-block.write" at org.eolang.io.console:120:8
  ⇢  9) Error in "Φ.org.eolang.io.console.posix-console.write.output-block.write.φ" at org.eolang.io.console:121:10
  ⇢ 10) Error in "Φ.org.eolang.io.console.posix-console.write.output-block.write.φ.ρ" at org.eolang.io.console:122:12
  ⇢ 11) Error in "Φ.org.eolang.seq.φ" at org.eolang.seq:12:2
  ⇢ 12) Error in "Φ.org.eolang.false.if" at org.eolang.false:16:2
  ⇢ 13) Error in "Φ.org.eolang.false.if.φ" at org.eolang.false:16:2
  ⇢ 14) Error in "Φ.org.eolang.seq.φ.α1" at org.eolang.seq:15:4
  ⇢ 15) Error in "Φ.org.eolang.false.if" at org.eolang.false:16:2
  ⇢ 16) Error in "Φ.org.eolang.false.if.φ" at org.eolang.false:16:2
  ⇢ 17) Error in "Φ.org.eolang.seq.φ.α1.α1" at org.eolang.seq:18:6
  ⇢ 18) Error in "Φ.org.eolang.seq.loop" at org.eolang.seq:25:2
  ⇢ 19) Error in "Φ.org.eolang.seq.loop.φ" at org.eolang.seq:26:4
  ⇢ 20) Error in "Φ.org.eolang.seq.loop.φ.ρ" at org.eolang.seq:27:6
  ⇢ 21) Error in "Φ.org.eolang.true.and" at org.eolang.true:20:2
  ⇢ 22) Error in "Φ.org.eolang.true.and.φ" at org.eolang.true:20:5
  ⇢ 23) Error in "Φ.org.eolang.bytes.eq" at org.eolang.bytes:70:2
  ⇢ 24) Error in "Φ.org.eolang.true.and.φ.α0" at org.eolang.true:20:9
  ⇢ 25) Error in "Φ.org.eolang.seq.loop.φ.ρ.α0" at org.eolang.seq:29:8
  ⇢ 26) Error in "Φ.org.eolang.seq.loop" at org.eolang.seq:25:2
  ⇢ 27) Error in "Φ.org.eolang.seq.loop.φ" at org.eolang.seq:26:4
  ⇢ 28) Error in "Φ.org.eolang.false.if" at org.eolang.false:16:2
  ⇢ 29) Error in "Φ.org.eolang.false.if.φ" at org.eolang.false:16:2
  ⇢ 30) Error in "Φ.org.eolang.seq.loop.φ.α1" at org.eolang.seq:31:6
  ⇢ 31) Error in "Φ.org.eolang.seq.loop.φ.α1.ρ" at org.eolang.seq:32:36
  ⇢ 32) Error in "Φ.org.eolang.seq.loop.φ.α1.ρ.ρ" at org.eolang.seq:32:28
  ⇢ 33) Error in "Φ.org.eolang.seq.loop.φ.α1.ρ.ρ.ρ" at org.eolang.seq:32:9
  ⇢ 34) Error in "Φ.org.eolang.dataized.φ" at org.eolang.dataized:37:2
Dataized to org.eolang.error with org.eolang.dataized.φ.α1.φ.α0 inside, at:
  ⇢ 1) Error in "Φ.org.eolang.dataized.φ.α1.φ.Δ" at org.eolang.dataized:39:4
Dataized to org.eolang.error with org.eolang.dataized.φ.α1.φ.α0 inside, at:
  ⇢  1) Error in "Φ.sandbox.app.φ.Δ" at sandbox.app:10:2
  ⇢  2) Error in "Φ.org.eolang.io.stdout.φ.Δ" at org.eolang.io.stdout:19:2
  ⇢  3) Error in "Φ.org.eolang.seq.φ.Δ" at org.eolang.seq:12:2
  ⇢  4) Error in "Φ.org.eolang.false.if.Δ" at org.eolang.false:16:2
  ⇢  5) Error in "Φ.org.eolang.false.if.φ.Δ" at org.eolang.false:16:2
  ⇢  6) Error in "Φ.org.eolang.seq.φ.α1.Δ" at org.eolang.seq:15:4
  ⇢  7) Error in "Φ.org.eolang.false.if.Δ" at org.eolang.false:16:2
  ⇢  8) Error in "Φ.org.eolang.false.if.φ.Δ" at org.eolang.false:16:2
  ⇢  9) Error in "Φ.org.eolang.seq.φ.α1.α1.Δ" at org.eolang.seq:18:6
  ⇢ 10) Error in "Φ.org.eolang.seq.loop.Δ" at org.eolang.seq:25:2
  ⇢ 11) Error in "Φ.org.eolang.seq.loop.φ" at org.eolang.seq:26:4
  ⇢ 12) Error in "Φ.org.eolang.seq.loop.φ.ρ" at org.eolang.seq:27:6
  ⇢ 13) Error in "Φ.org.eolang.true.and" at org.eolang.true:20:2
  ⇢ 14) Error in "Φ.org.eolang.true.and.φ" at org.eolang.true:20:5
  ⇢ 15) Error in "Φ.org.eolang.bytes.eq" at org.eolang.bytes:70:2
  ⇢ 16) Error in "Φ.org.eolang.true.and.φ.α0" at org.eolang.true:20:9
  ⇢ 17) Error in "Φ.org.eolang.seq.loop.φ.ρ.α0" at org.eolang.seq:29:8
  ⇢ 18) Error in "Φ.org.eolang.seq.loop" at org.eolang.seq:25:2
  ⇢ 19) Error in "Φ.org.eolang.seq.loop.φ" at org.eolang.seq:26:4
  ⇢ 20) Error in "Φ.org.eolang.false.if" at org.eolang.false:16:2
  ⇢ 21) Error in "Φ.org.eolang.false.if.φ" at org.eolang.false:16:2
  ⇢ 22) Error in "Φ.org.eolang.seq.loop.φ.α1" at org.eolang.seq:31:6
  ⇢ 23) Error in "Φ.org.eolang.seq.loop.φ.α1.ρ" at org.eolang.seq:32:36
  ⇢ 24) Error in "Φ.org.eolang.seq.loop.φ.α1.ρ.ρ" at org.eolang.seq:32:28
  ⇢ 25) Error in "Φ.org.eolang.seq.loop.φ.α1.ρ.ρ.ρ" at org.eolang.seq:32:9
  ⇢ 26) Error in "Φ.org.eolang.dataized.φ" at org.eolang.dataized:37:2
org.eolang.PhSafe@290d210e(Δ = [0x54686520-61747472-69627574-6520226C-656E6774-68222069-73206E6F-7420696E-69746961-6C697A65-642C2063-616E2774-20726561-64] = "The attribute "length" is not initialized, can't read")
```

Expected behaviour: 
```
I am 10 years old!
```

`eo` version:

```  
0.52.0
```

System:

```
Ubuntu 24.04.2
```

**Comment by Suban05** [comment]
@maxonfjvipon what am I doing wrong?

**Comment by maxonfjvipon** [comment]
@Suban05 the second argument of `sprintf` must be a `tuple`
```
sprintf
  "Age %d"
  * age
```

**Comment by Suban05** [comment]
@maxonfjvipon I tried this one:

```
# Outputs the age.
[args] > app
  args.at 0 > age
  stdout > @
    sprintf
      "I am %d years old!"
      * age
```
I get the same error

```
The attribute "length" is not initialized, can't read
```

**Comment by maxonfjvipon** [comment]
@Suban05 which version of compiler and home-tag do you use?

**Comment by Suban05** [comment]
@maxonfjvipon 0.52.0

I created an example repo: https://github.com/Suban05/eo-greet

maybe it will help

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.54.0`

**Comment by maxonfjvipon** [comment]
@Suban05 please try new version `0.53.0`, should work

**Comment by Suban05** [comment]
@maxonfjvipon it seems that this error has been fixed, but the sample program I gave still doesn't work. now, instead of the old error, another one appears. Then I close this issue and create a new ticket?

**Comment by maxonfjvipon** [comment]
@Suban05 it seems we introduced some breaking changes in `0.53.0` release, so we need to [update](https://github.com/objectionary/eoc/issues/470) `eoc` also, let's wait for this ticket is resolved

**Comment by Suban05** [comment]
@maxonfjvipon I see that version 0.54.1 has appeared. I tried updating the version in my [demo repository](https://github.com/Suban05/eo-greet), but I still can't pass the arguments to `sprintf`, that's what error I get: https://github.com/Suban05/eo-greet/actions/runs/13951046978/job/39050360048
please help

**Comment by maxonfjvipon** [comment]
@Suban05 yes, the problem is still here, I'm working on it

**Comment by maxonfjvipon** [comment]
@Suban05 please update eoc and try it with last version of EO

**Comment by Suban05** [comment]
@maxonfjvipon I updated the EO version, but I still get the error:
https://github.com/Suban05/eo-greet/actions/runs/14148551351/job/39638859734

**Comment by maxonfjvipon** [comment]
@Suban05 all arguments passed via console are strings, but you use `%d` formater, which is wrong. Try to use `%s` or convert string to number via `scanf`

**Comment by yegor256** [comment]
@Suban05 if the nature of the error changes, it's better to close the ticket and open a new one, with a new description

**Comment by Suban05** [comment]
@maxonfjvipon thanks a lot! your advice helped. and now it's ok, the program works. I think we can close this issue, thanks!
