### ISSUE TITLE
pdd-lint is broken

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#804]
Every build has the same error:

```
ERROR:  Error installing pdd:
  	ERROR: Failed to build gem native extension.
  
      current directory: /usr/lib/ruby/gems/2.7.0/gems/ruby-filemagic-0.7.3/ext/filemagic
  /usr/bin/ruby -I /usr/lib/ruby/2.7.0 -r ./siteconf20220630-98-yqkph1.rb extconf.rb
  checking for -lgnurx... no
  checking for magic_open() in -lmagic... no
  *** ERROR: missing required library to compile this module
  *** extconf.rb failed ***
  Could not create Makefile due to some reason, probably lack of necessary
  libraries and/or headers.  Check the mkmf.log file for more details.  You may
  need configuration options.
```

**Comment by yegor256** [comment]
@Graur this should fix it: https://github.com/g4s8/pdd-action/pull/5

**Comment by mximp** [comment]
Still broken: https://github.com/objectionary/eo/runs/7147936049?check_suite_focus=true
