### ISSUE TITLE
`list.eq` freezes

### ISSUE THREAD

**Issue by kerelape** [objectionary/eo#913]
https://github.com/objectionary/eo/blob/587c476e89c8e64d8aa6e49cc48c158caaec4fe0/eo-runtime/src/test/eo/org/eolang/collections/list-tests.eo#L326-L334

If I remove `nop`(#837) from this test and do `mvn clean install -Pqulice` the build gets stuck on this test

**Comment by Graur** [comment]
@kerelape There is no `eq` object in `array` anymore. So you can't compare arrays without a `list` decorator.

**Comment by mximp** [comment]
@Graur @kerelape maybe we could amend `list.eq` so that it would wrap internally arrays with list when comparing them?

**Comment by Graur** [comment]
@mximp `list` has already decorate the given `array`, so I think there is no need to wrap it. 
e.g.
```
* 1 2 > a
list (* 1 2) > b
b.eq a > @ 
```
and 
```
list (* 1 2) > a
list (* 1 2) > b
b.eq a > @ 
```
will work

**Comment by yegor256** [comment]
@kerelape I believe, #917 should fix the "hanging" part of the problem

**Comment by Graur** [comment]
@kerelape Do you still have an issue?

**Comment by kerelape** [comment]
@Graur the test is still broken. Maybe there is another reason for this issue?

**Comment by Graur** [comment]
@kerelape I believe you can fix it. See my first comment.

**Comment by kerelape** [comment]
@Graur sorry, didn't notice it. Wrapping `a`, `b`, and `* "w" a` with `list` fixes the test.
